[package]
name = "display-nvidia-mem"
version = "0.1.0"
authors = ["Árni Dagur <arni@dagur.eu>"]
edition = "2018"

[dependencies]
nvml-wrapper = "0.4.1"
quick-error = "1.1"
number_prefix = "0.3"

[profile.release]
lto = true
codegen-units = 1
