[package]
name = "display-battery"
version = "0.1.0"
authors = ["Árni Dagur <arni@dagur.eu>"]
edition = "2018"

[dependencies]
battery = "0.7.4"
quick-error = "1.1"
arraydeque = "0.4.5"

[profile.release]
lto = true
codegen-units = 1
