[window]
opacity = 0.50

[colors.bright]
black = "#808080"
blue = "#0066ff"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#fe0100"
white = "#FFFFFF"
yellow = "#feff00"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#000000"
blue = "#0066ff"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#fe0100"
white = "#d0d0d0"
yellow = "#feff00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 12

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"
